import { ClerkProvider } from "@clerk/nextjs/app-beta";
import "./globals.css";
import { Sidebar } from "@/sidebar/Sidebar";
import Providers from "@/providers";

export const metadata = {
	title: "Robots Are People Too",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body>
					<Providers>
						<Sidebar />
						<div className="ml-16 sm:ml-64 relative min-h-screen">
							{children}
						</div>
					</Providers>
				</body>
			</ClerkProvider>
		</html>
	);
}
