import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
// import Providers from "@/providers";

export const metadata = {
	title: "Robots Are People Too",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body>
					{children}
					{/* <Providers>{children}</Providers> */}
				</body>
			</ClerkProvider>
		</html>
	);
}
